import Head from 'next/head'
import Articles from '../components/Articles'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Api ile makale datası çekme</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Articles/>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}
